[workspace]
members = [
    "crates/rps",
    "crates/rps-sys",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mxpv/rps"
homepage = "https://github.com/GPUOpen-LibrariesAndSDKs/RenderPipelineShaders"
