name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: Docs
    runs-on: [macos-12]
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - run: cargo doc --no-deps
        env:
          RUSTDOCFLAGS: -Dwarnings
