name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: Checks
    runs-on: [macos-12]
    timeout-minutes: 10

    strategy:
      matrix:
        os: [macos-12]
        features: [vk]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - run: cargo check --examples --tests --features ${{ matrix.features }}
      - run: cargo clippy --features ${{ matrix.features }} -- -D warnings
      - run: cargo test --features ${{ matrix.features }}
      - run: cargo doc --no-deps --features ${{ matrix.features }}
        env:
          RUSTDOCFLAGS: -Dwarnings
