name: CI
on: [push, pull_request]

jobs:
  checks:
    name: Checks
    timeout-minutes: 15
    runs-on: [macos-12, ubuntu-20.04, windows-2022]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - run: cargo check --examples --tests --all-targets --all-features
      - run: cargo fmt --all -- --check --files-with-diff
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo test --all-features
